version: '3'

services:
  cassandra:
    image: 'cassandra:3.11.4'
    container_name: grpc_demo
    ports:
      - '9042:9042'
    environment:
      - "MAX_HEAP_SIZE=2048M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - ./build/cassandra:/var/lib/cassandra
