// Code generated by protoc-gen-go. DO NOT EDIT.
// source: list.proto

package list

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type List struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *List) Reset()         { *m = List{} }
func (m *List) String() string { return proto.CompactTextString(m) }
func (*List) ProtoMessage()    {}
func (*List) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{0}
}

func (m *List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_List.Unmarshal(m, b)
}
func (m *List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_List.Marshal(b, m, deterministic)
}
func (m *List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_List.Merge(m, src)
}
func (m *List) XXX_Size() int {
	return xxx_messageInfo_List.Size(m)
}
func (m *List) XXX_DiscardUnknown() {
	xxx_messageInfo_List.DiscardUnknown(m)
}

var xxx_messageInfo_List proto.InternalMessageInfo

func (m *List) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *List) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *List) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetListReq struct {
	ListId               string   `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListReq) Reset()         { *m = GetListReq{} }
func (m *GetListReq) String() string { return proto.CompactTextString(m) }
func (*GetListReq) ProtoMessage()    {}
func (*GetListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{1}
}

func (m *GetListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListReq.Unmarshal(m, b)
}
func (m *GetListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListReq.Marshal(b, m, deterministic)
}
func (m *GetListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListReq.Merge(m, src)
}
func (m *GetListReq) XXX_Size() int {
	return xxx_messageInfo_GetListReq.Size(m)
}
func (m *GetListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetListReq proto.InternalMessageInfo

func (m *GetListReq) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

type ListResp struct {
	Items                []*List  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{2}
}

func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (m *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(m, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetItems() []*List {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetOneListReq struct {
	ListId               string   `protobuf:"bytes,1,opt,name=list_id,json=listId,proto3" json:"list_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneListReq) Reset()         { *m = GetOneListReq{} }
func (m *GetOneListReq) String() string { return proto.CompactTextString(m) }
func (*GetOneListReq) ProtoMessage()    {}
func (*GetOneListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{3}
}

func (m *GetOneListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneListReq.Unmarshal(m, b)
}
func (m *GetOneListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneListReq.Marshal(b, m, deterministic)
}
func (m *GetOneListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneListReq.Merge(m, src)
}
func (m *GetOneListReq) XXX_Size() int {
	return xxx_messageInfo_GetOneListReq.Size(m)
}
func (m *GetOneListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneListReq proto.InternalMessageInfo

func (m *GetOneListReq) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

type ListItem struct {
	Item                 *List    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItem) Reset()         { *m = ListItem{} }
func (m *ListItem) String() string { return proto.CompactTextString(m) }
func (*ListItem) ProtoMessage()    {}
func (*ListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{4}
}

func (m *ListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItem.Unmarshal(m, b)
}
func (m *ListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItem.Marshal(b, m, deterministic)
}
func (m *ListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItem.Merge(m, src)
}
func (m *ListItem) XXX_Size() int {
	return xxx_messageInfo_ListItem.Size(m)
}
func (m *ListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItem.DiscardUnknown(m)
}

var xxx_messageInfo_ListItem proto.InternalMessageInfo

func (m *ListItem) GetItem() *List {
	if m != nil {
		return m.Item
	}
	return nil
}

type RequestTrack struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTrack) Reset()         { *m = RequestTrack{} }
func (m *RequestTrack) String() string { return proto.CompactTextString(m) }
func (*RequestTrack) ProtoMessage()    {}
func (*RequestTrack) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{5}
}

func (m *RequestTrack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTrack.Unmarshal(m, b)
}
func (m *RequestTrack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTrack.Marshal(b, m, deterministic)
}
func (m *RequestTrack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTrack.Merge(m, src)
}
func (m *RequestTrack) XXX_Size() int {
	return xxx_messageInfo_RequestTrack.Size(m)
}
func (m *RequestTrack) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTrack.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTrack proto.InternalMessageInfo

func (m *RequestTrack) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type SetListsResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode           int32    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetListsResponse) Reset()         { *m = SetListsResponse{} }
func (m *SetListsResponse) String() string { return proto.CompactTextString(m) }
func (*SetListsResponse) ProtoMessage()    {}
func (*SetListsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af793ce248ee1bf0, []int{6}
}

func (m *SetListsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetListsResponse.Unmarshal(m, b)
}
func (m *SetListsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetListsResponse.Marshal(b, m, deterministic)
}
func (m *SetListsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetListsResponse.Merge(m, src)
}
func (m *SetListsResponse) XXX_Size() int {
	return xxx_messageInfo_SetListsResponse.Size(m)
}
func (m *SetListsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetListsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetListsResponse proto.InternalMessageInfo

func (m *SetListsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SetListsResponse) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*List)(nil), "list.List")
	proto.RegisterType((*GetListReq)(nil), "list.GetListReq")
	proto.RegisterType((*ListResp)(nil), "list.ListResp")
	proto.RegisterType((*GetOneListReq)(nil), "list.GetOneListReq")
	proto.RegisterType((*ListItem)(nil), "list.ListItem")
	proto.RegisterType((*RequestTrack)(nil), "list.RequestTrack")
	proto.RegisterType((*SetListsResponse)(nil), "list.SetListsResponse")
}

func init() {
	proto.RegisterFile("list.proto", fileDescriptor_af793ce248ee1bf0)
}

var fileDescriptor_af793ce248ee1bf0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xf3, 0x50,
	0x10, 0xfd, 0xd2, 0xa6, 0xc9, 0xe7, 0x44, 0x43, 0x19, 0xa1, 0x86, 0x2e, 0x4a, 0xb9, 0x20, 0x04,
	0xd1, 0x22, 0x2d, 0x3e, 0x80, 0xb8, 0xd0, 0x42, 0x41, 0x48, 0xdd, 0x4b, 0x4c, 0x06, 0x09, 0xa6,
	0x49, 0xcd, 0xbd, 0xf1, 0x55, 0x7d, 0x1d, 0xef, 0x4f, 0xda, 0xc4, 0x6c, 0x5c, 0xe5, 0xce, 0xcc,
	0x99, 0x33, 0xe7, 0x1c, 0x02, 0x90, 0x67, 0x5c, 0x2c, 0xf6, 0x55, 0x29, 0x4a, 0xb4, 0xd5, 0x9b,
	0x3d, 0x81, 0xbd, 0x91, 0x5f, 0xf4, 0x61, 0x90, 0xa5, 0x81, 0x35, 0xb7, 0xc2, 0x93, 0x48, 0xbe,
	0x30, 0x00, 0x37, 0x29, 0x0b, 0x41, 0x85, 0x08, 0x06, 0xba, 0x79, 0x28, 0x71, 0x02, 0x4e, 0xcd,
	0xa9, 0x5a, 0xa7, 0xc1, 0x50, 0x0f, 0x9a, 0x8a, 0x5d, 0x02, 0x3c, 0x92, 0x50, 0x64, 0x11, 0x7d,
	0xe2, 0x05, 0xb8, 0x8a, 0xff, 0xf5, 0x48, 0xea, 0xa8, 0x52, 0xc2, 0xae, 0xe1, 0xbf, 0xc1, 0xf0,
	0x3d, 0xce, 0x61, 0x94, 0x09, 0xda, 0x71, 0x09, 0x19, 0x86, 0xde, 0x12, 0x16, 0x5a, 0x9e, 0x1e,
	0x9b, 0x01, 0x0b, 0xe1, 0x4c, 0x92, 0x3e, 0x17, 0xf4, 0x27, 0xef, 0x95, 0xe1, 0x5d, 0xcb, 0x35,
	0x9c, 0x81, 0xad, 0xd6, 0x35, 0xe2, 0x37, 0xad, 0xee, 0xb3, 0x19, 0x9c, 0x4a, 0xae, 0x9a, 0xb8,
	0x78, 0xa9, 0xe2, 0xe4, 0xa3, 0x6f, 0x9e, 0x6d, 0x60, 0xbc, 0x35, 0x56, 0xb8, 0xd2, 0x59, 0x16,
	0x9c, 0x54, 0x20, 0x3b, 0xe2, 0x3c, 0x7e, 0xa7, 0x06, 0x78, 0x28, 0xe5, 0x35, 0xe0, 0x22, 0x16,
	0x35, 0x7f, 0x28, 0x53, 0xd2, 0x69, 0x8d, 0xa2, 0x4e, 0x67, 0xf9, 0x6d, 0x81, 0xa7, 0xb8, 0xb6,
	0x54, 0x7d, 0x65, 0x09, 0xe1, 0x0d, 0xb8, 0x4d, 0x50, 0x38, 0x36, 0xd2, 0xda, 0xdc, 0xa6, 0x7e,
	0x47, 0xac, 0x3c, 0xcd, 0xfe, 0xe1, 0x1d, 0xf8, 0x6d, 0x04, 0xda, 0xde, 0xf9, 0x71, 0xab, 0x0d,
	0xa6, 0xbb, 0xa8, 0x41, 0x2b, 0xf0, 0x24, 0xe0, 0x3e, 0xcf, 0xb5, 0x0d, 0x44, 0x33, 0xee, 0xda,
	0xee, 0xdf, 0xba, 0xb5, 0x94, 0xb4, 0xc6, 0x38, 0x76, 0x52, 0x9b, 0x4e, 0xcc, 0xbb, 0x9f, 0xc9,
	0x9b, 0xa3, 0xff, 0xa4, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x2b, 0x28, 0x98, 0x57,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ListServiceClient is the client API for ListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ListServiceClient interface {
	GetList(ctx context.Context, in *GetListReq, opts ...grpc.CallOption) (*ListResp, error)
	GetOneListItem(ctx context.Context, in *GetOneListReq, opts ...grpc.CallOption) (*ListItem, error)
	GetAllLists(ctx context.Context, in *RequestTrack, opts ...grpc.CallOption) (ListService_GetAllListsClient, error)
	SetList(ctx context.Context, in *List, opts ...grpc.CallOption) (*SetListsResponse, error)
}

type listServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListServiceClient(cc grpc.ClientConnInterface) ListServiceClient {
	return &listServiceClient{cc}
}

func (c *listServiceClient) GetList(ctx context.Context, in *GetListReq, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := c.cc.Invoke(ctx, "/list.ListService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listServiceClient) GetOneListItem(ctx context.Context, in *GetOneListReq, opts ...grpc.CallOption) (*ListItem, error) {
	out := new(ListItem)
	err := c.cc.Invoke(ctx, "/list.ListService/GetOneListItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listServiceClient) GetAllLists(ctx context.Context, in *RequestTrack, opts ...grpc.CallOption) (ListService_GetAllListsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ListService_serviceDesc.Streams[0], "/list.ListService/GetAllLists", opts...)
	if err != nil {
		return nil, err
	}
	x := &listServiceGetAllListsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ListService_GetAllListsClient interface {
	Recv() (*ListResp, error)
	grpc.ClientStream
}

type listServiceGetAllListsClient struct {
	grpc.ClientStream
}

func (x *listServiceGetAllListsClient) Recv() (*ListResp, error) {
	m := new(ListResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *listServiceClient) SetList(ctx context.Context, in *List, opts ...grpc.CallOption) (*SetListsResponse, error) {
	out := new(SetListsResponse)
	err := c.cc.Invoke(ctx, "/list.ListService/SetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListServiceServer is the server API for ListService service.
type ListServiceServer interface {
	GetList(context.Context, *GetListReq) (*ListResp, error)
	GetOneListItem(context.Context, *GetOneListReq) (*ListItem, error)
	GetAllLists(*RequestTrack, ListService_GetAllListsServer) error
	SetList(context.Context, *List) (*SetListsResponse, error)
}

// UnimplementedListServiceServer can be embedded to have forward compatible implementations.
type UnimplementedListServiceServer struct {
}

func (*UnimplementedListServiceServer) GetList(ctx context.Context, req *GetListReq) (*ListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedListServiceServer) GetOneListItem(ctx context.Context, req *GetOneListReq) (*ListItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOneListItem not implemented")
}
func (*UnimplementedListServiceServer) GetAllLists(req *RequestTrack, srv ListService_GetAllListsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllLists not implemented")
}
func (*UnimplementedListServiceServer) SetList(ctx context.Context, req *List) (*SetListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetList not implemented")
}

func RegisterListServiceServer(s *grpc.Server, srv ListServiceServer) {
	s.RegisterService(&_ListService_serviceDesc, srv)
}

func _ListService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).GetList(ctx, req.(*GetListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListService_GetOneListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).GetOneListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/GetOneListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).GetOneListItem(ctx, req.(*GetOneListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListService_GetAllLists_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestTrack)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListServiceServer).GetAllLists(m, &listServiceGetAllListsServer{stream})
}

type ListService_GetAllListsServer interface {
	Send(*ListResp) error
	grpc.ServerStream
}

type listServiceGetAllListsServer struct {
	grpc.ServerStream
}

func (x *listServiceGetAllListsServer) Send(m *ListResp) error {
	return x.ServerStream.SendMsg(m)
}

func _ListService_SetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListServiceServer).SetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/list.ListService/SetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListServiceServer).SetList(ctx, req.(*List))
	}
	return interceptor(ctx, in, info, handler)
}

var _ListService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "list.ListService",
	HandlerType: (*ListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetList",
			Handler:    _ListService_GetList_Handler,
		},
		{
			MethodName: "GetOneListItem",
			Handler:    _ListService_GetOneListItem_Handler,
		},
		{
			MethodName: "SetList",
			Handler:    _ListService_SetList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllLists",
			Handler:       _ListService_GetAllLists_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "list.proto",
}
